### ISSUE TITLE
Compilation Error on macos (clang?)

### ISSUE THREAD

**Issue by BluSyn** [chjj/mako#2]
System:
Apple M1 Pro (arm64)
`cmake version 3.21.4`
`Apple clang version 13.0.0 (clang-1300.0.29.3)`

Note: This error did *not* appear when compiling on Arch Linux running x86-64. (`gcc (GCC) 11.1.0`)

Error:
```
[  3%] Building C object CMakeFiles/mako_io.dir/src/io/loop.c.o
./mako/src/io/loop.c:1782:1: error: extraneous closing brace ('}')
````

Remedy:
Deleting trailing `}` in `loop.c:1771` resolved the error.
Compilation completed successfully after this change.

However, I don't know if this is a breaking change warranting further tweaks.

Good news: I have successfully started syncing mainnet without further issue on macOS w/ Apple ARM SoC (so far).

**Comment by chjj** [comment]
Probably caused by a refactor of the event loop and not testing the poll backend afterwards. Linux will use `epoll` and OSX will use `poll`. Will fix.
